#- name: Fish shell
#  block:
#  - apt_repository: repo=ppa:fish-shell/release-2 state=present
#  - apt: name=fish state=present


- name: Add APT repositories
  apt_repository: repo="{{ item }}" update_cache=yes state=present
  loop: "{{ repositories }}"

- name: Install APT packages
  apt: name="{{ packages }}" state=present

- name: Install Fish shell
  block:
    - apt_repository: repo=ppa:fish-shell/release-2 update_cache=yes
                      state=present
    - apt: name=fish state=present
    - shell: chsh -s /usr/bin/fish
    - get_url: url=https://get.oh-my.fish dest=/tmp/omf_install
    - shell: fish /tmp/omf_install --path=~/.local/share/omf --config=~/.config/omf --yes --verbose
