- name: Add APT repositories
  apt_repository: repo="{{ item }}" update_cache=yes state=present
  loop: "{{ repositories }}"

- name: Install APT packages
  apt: name="{{ packages }}" state=present

- name: Install snaps
  command: snap install {{ item }} --classic
  loop: "{{ snaps }}"

- name: Install Fish shell
  block:
    - apt_repository: repo=ppa:fish-shell/release-2 update_cache=yes
                      state=present
    - apt: name=fish state=present
    - shell: chsh -s /usr/bin/fish
    #- get_url: url=https://get.oh-my.fish dest=/tmp/omf_install
    #- shell: fish /tmp/omf_install --path=~/.local/share/omf --config=~/.config/omf --yes --verbose
    # Use set -x to set omf settings
    # Download nerd fonts.
    # https://github.com/ryanoasis/nerd-fonts/releases
    # sudo unzip <font.zip> -d /usr/share/local/fonts
    # sudo fc-cache -fv
    # select custom font from profile settings.

    sudo apt-add-repository ppa:fish-shell/release-2
sudo apt-get update
sudo apt-get install fish git
echo (which fish) | sudo tee -a /etc/shells
chsh -s (which fish)
curl -L http://get.oh-my.fish | fish
omf install bobthefish
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/FiraCode.zip
sudo unzip FiraCode.zip -d /usr/local/share/fonts/
sudo fc-cache -fv
set -U theme_nerd_fonts yes

# - name: Restore tweaktool settings


sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update -y
sudo apt-get install oracle-java8-installer -y
