- name: Check if git is installed
  apt: name=git state=present
  check_mode: true
  register: git_installed

- name: Install GIT
  apt: name=git state=present
  when: not git_installed.changed
  notify:
    - configure git

- name: Install APT packages
  apt: name="{{ apt_packages }}" state=present

- name: Install snaps
  command: snap install {{ item }} --classic
  loop: "{{ snaps }}"
  notify: "{{ item }} installed"

# Move below to personal ansible playbook
# - name: Create directories
#   file: path="/home/{{ ansible_env.SUDO_USER }}/{{ item }}" state=directory
#         owner="{{ ansible_env.SUDO_USER }}" group="{{ ansible_env.SUDO_USER }}"
#   loop: "{{ directories }}"
