- include_role:
    name: common

- name: Check if git is installed
  apt: name=git state=present
  check_mode: true
  register: git_installed

- name: Install GIT
  apt: name=git state=present
  when: not git_installed.changed
  notify:
    - configure git

# Move below to personal ansible playbook
# - name: Create directories
#   file: path="/home/{{ ansible_env.SUDO_USER }}/{{ item }}" state=directory
#         owner="{{ ansible_env.SUDO_USER }}" group="{{ ansible_env.SUDO_USER }}"
#   loop: "{{ directories }}"
