- name: Install APT packages
  apt: name="{{ packages }}" state=present

- name: Install snaps
  command: snap install {{ item }} --classic
  loop: "{{ snaps }}"
   
- name: Create directories
  file: path="/home/{{ ansible_env.SUDO_USER }}/{{ item }}" state=directory
        owner="{{ ansible_env.SUDO_USER }}" group="{{ ansible_env.SUDO_USER }}"
  loop: "{{ directories }}"
